#ifndef _CONFIG_H_
#define _CONFIG_H_

#include "live.h"

#define C_L      1
#define C_C      3
const State C[C_L][C_C] = { 
    {ALIVE, ALIVE, ALIVE}
};

#define V_L      1
#define V_C      4
const State V[V_L][V_C] = { 
    {ALIVE, ALIVE, ALIVE, ALIVE}
};

#define B_L      1
#define B_C      5
const State B[B_L][B_C] = { 
    {ALIVE, ALIVE, ALIVE, ALIVE, ALIVE}
};

#define M_L      4
#define M_C      3
const State M[M_L][M_C] = { 
    {DEAD, ALIVE, ALIVE},
    {ALIVE, DEAD, ALIVE},
    {ALIVE, DEAD, ALIVE},
    {DEAD, ALIVE, ALIVE}
};

#define L_L      4
#define L_C      3
const State L[L_L][L_C] = { 
    {DEAD, ALIVE, ALIVE},
    {ALIVE, DEAD, ALIVE},
    {ALIVE, DEAD, ALIVE},
    {DEAD, ALIVE, DEAD}
};

#define A_L     3
#define A_C     5
const State A[A_L][A_C] = { 
    {DEAD, ALIVE, DEAD, DEAD, DEAD},
    {ALIVE, ALIVE, ALIVE, ALIVE, ALIVE},
    {DEAD, DEAD, DEAD, DEAD, DEAD}
};

#define K_L     3
#define K_C     4
const State K[K_L][K_C] = { 
    {DEAD, DEAD, ALIVE, ALIVE},
    {DEAD, ALIVE, ALIVE, DEAD},
    {ALIVE, ALIVE, DEAD, DEAD},
};

#define J_L     3
#define J_C     3
const State J[J_L][J_C] = { 
    {DEAD, ALIVE, ALIVE},
    {ALIVE, ALIVE, DEAD},
    {DEAD, ALIVE, DEAD},
};

#define H_L     5
#define H_C     5
const State H[H_L][H_C] = { 
    {ALIVE, DEAD, ALIVE, DEAD, ALIVE},
    {ALIVE, DEAD, DEAD, DEAD, ALIVE},
    {ALIVE, DEAD, DEAD, DEAD, ALIVE},
    {ALIVE, DEAD, DEAD, DEAD, ALIVE},
    {ALIVE, DEAD, ALIVE, DEAD, ALIVE},
};

#define G_L     1
#define G_C     10
const State G[G_L][G_C] = { 
    {ALIVE, ALIVE, ALIVE, ALIVE, ALIVE, ALIVE, ALIVE, ALIVE, ALIVE, ALIVE}
};

#define F_L     3
#define F_C     10
const State F[F_L][F_C] = { 
    {DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD},
    {DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE},
    {ALIVE, ALIVE, ALIVE, DEAD, DEAD, DEAD, ALIVE, ALIVE, ALIVE}
};

#define D_L     3
#define D_C     10
const State D[D_L][D_C] = { 
    {DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD},
    {DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE},
    {ALIVE, ALIVE, ALIVE, DEAD, DEAD, DEAD, ALIVE, ALIVE, ALIVE}
};

#define Q_L     9
#define Q_C     36
const State Q[Q_L][Q_C] = { 
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, ALIVE},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, ALIVE},
    {ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, ALIVE, DEAD, ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIVE, ALIVE, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
};

#endif